---
title: "Covid19DataAnalysis"
author: "Ethan field"
date: "6/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(maps)
```

```{r}
# data import
usCensus <- read_csv("co-est2019-alldata.csv")

covCounties <- read_csv("./covid-19-data/us-counties.csv", col_types = "Dcccnn")

covStates <- read_csv("./covid-19-data/us-states.csv", col_types = "Dccnn")

covUS <- read_csv("./covid-19-data/us.csv")

# add fips to usCensus by concat state + county numbers

#adding change in cases
covCounties <- group_by(covCounties, fips) %>%
  mutate(casesChange = cases - lag(cases)) %>%
  mutate(deathsChange = deaths - lag(deaths))

covStates <- group_by(covStates, state) %>%
  mutate(casesChange = cases - lag(cases)) %>%
  mutate(deathsChange = deaths - lag(deaths))

covUS <- covUS %>%
  mutate(casesChange = cases - lag(cases)) %>%
  mutate(deathsChange = deaths - lag(deaths))


```


```{r}

paCounties <- filter(covCounties, state == "Pennsylvania")

unionPAcov <- filter(paCounties, county == "Union")

usefulCensus <- select(usCensus, SUMLEV, REGION, DIVISION, STATE, COUNTY, STNAME, CTYNAME, POPESTIMATE2019) %>%
  mutate(fips = paste0(STATE, COUNTY))

usFIPS <- county.fips

covCounties <- left_join(covCounties, usefulCensus, by = "fips") %>%
  mutate(casesNorm = cases/POPESTIMATE2019) %>%
  mutate(deathsNorm = deaths/POPESTIMATE2019) %>%
  mutate(casesChangeNorm = casesChange/POPESTIMATE2019) %>%
  mutate (deathsChangeNorm = deathsChange/POPESTIMATE2019)

```


```{r}
#plot of staes by cases
qplot(x = date, y = cases, data = covStates, color = state)

qplot(x = date, y = casesChange, data = covUS)

#demo of cases and deaths for all counties
ggplot(data = paCounties) +
  geom_area(aes(x = date, y = cases, color = "red"), position = "stack") +
  geom_area(aes(x = date, y = deaths, color = "blue"), position = "stack")

paCountyMapData <- map_data(paCountyMap)

ggplot(data = paCounties) +
  geom_map(aes(map_id = county, fill = cases), map = map_data(paCountyMap))+
  expand_limits(x = )


# try to make map that displays the correlation of difference from national average in the popular vote for 2016 national election with
# change in Covid-19 cases from the lowest after 4/1. 


# add normalizaation for population
# 
# still try to find the data for residential land area by county to try to compare population densities in various counties

```

```{r}



```
